!!python/object/apply:collections.OrderedDict
- - - D:\projects\BashNIPIneft-dev\db.hdf5
    - !!python/tuple
      - 8
      - 8
  - - D:/projects/BashNIPIneft-dev/10.hdf5
    - !!python/tuple
      - 8
      - 8
