!!python/object/apply:collections.OrderedDict
- - - db2.hdf5
    - dimensions: !!python/tuple
      - 8
      - 8
      max: 9999
      min: 5
  - - db2.hdf51
    - dimensions: !!python/tuple
      - 16
      - 16
      max: 7
      min: 6
