!!python/object/apply:collections.OrderedDict
- - - D:\pylerning\BashNIPIneft\db.hdf5
    - !!python/tuple
      - 8
      - 8
  - - D:/pylerning/BashNIPIneft/2.hdf5
    - !!python/tuple
      - 8
      - 8
  - - D:/pylerning/BashNIPIneft/5.hdf5
    - !!python/tuple
      - 8
      - 8
  - - D:/pylerning/BashNIPIneft/0.hdf5
    - !!python/tuple
      - 8
      - 8
  - - D:/pylerning/BashNIPIneft/9.hdf5
    - !!python/tuple
      - 8
      - 8
